### ISSUE TITLE
M551 Conflict

### ISSUE THREAD

**Issue by HebigT** [HaythamB/TAMV#28]
Using TAMV with great success but noticed this:

I had M551 and a password in my config ( i'm on a shared network).

This prevented TAMV from connecting to the duet. (Duet 2 RRF 3.2.2)

https://reprap.org/wiki/G-code#M551:_Set_Password

**Comment by HaythamB** [comment]
Its quite late from when this was submitted, but its working with passwords now. Defaults to "reprap" as per Duet's configurations, and you can use your own password. 

Tested on my Duet 2 board, and should work for Duet 3 boards in standalone mode.

**Comment by HebigT** [comment]
> Its quite late from when this was submitted, but its working with passwords now. Defaults to "reprap" as per Duet's configurations, and you can use your own password.
> 
> Tested on my Duet 2 board, and should work for Duet 3 boards in standalone mode and in SBC mode

Awesome, thank you for the update!
