### ISSUE TITLE
Debian Bullseye does not support qt5-default

### ISSUE THREAD

**Issue by jaysuk** [HaythamB/TAMV#38]
https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5902890.html

See above. Therefore TAMV does not launch on raspberry pi os bullseye

**Comment by HaythamB** [comment]
Just found out Qt5 is not supported on Debian. Ubuntu or openSUSE or Raspbian derivatives are supported.

**Comment by jaysuk** [comment]
Still doesn't work on latest raspbian-os builds as QT5 is no longer installed
