### ISSUE TITLE
Install Issue (QT5)

### ISSUE THREAD

**Issue by Festivejelly** [HaythamB/TAMV#42]
I seem to be getting an error when its trying to install the openCV.

```
CMake Error at cmake/OpenCVFindLibsGUI.cmake:18 (find_package):
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake
```

I guess it has some requirements? This was on a new raspberry pi 4 with the latest version of Raspian.

**Comment by ekozan** [comment]
try 
`
    sudo apt install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
`

**Comment by HaythamB** [comment]
Also try running:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python3-matplotlib
sudo apt-get install python3-pyqt5
```

That should solve your issue. Dependencies with python isn't the smoothest thing in the world, sorry!
